### PR TITLE
Fix for Kernel Version 5.15.32 v8+

### PR DESCRIPTION
**Pull request by dheeraj-rn**
Merged PR https://github.com/fastoe/RTL8812BU_for_Raspbian/pull/14 into branch [v5.8.7](https://github.com/fastoe/RTL8812BU_for_Raspbian/tree/v5.8.7)

### CODE REVIEW

**Comment by kressinluiz** [comment]
i`ve tested on 3B+ and it works, thanks

**Comment by hossein-mohseni** [comment]
i've tested on 4 B Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux didn't work for me :(

**Comment by dheeraj-rn** [comment]
@hossein-mohseni The whole driver or just the Monitor mode?

**Comment by hossein-mohseni** [comment]
> 

the whole driver!

**Pull request merged**
